<a href="https://colab.research.google.com/github/AqsaAamena/Basic-Python-Projects/blob/main/Assignment_14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1. (Array Properties)
Create a 2D array of shape (5, 6) filled with random integers between 10 and 100.
Print the following:
Shape of the array
Total number of elements (size)
Data type (dtype)

In [3]:
import numpy as np


In [ ]:
two_d=np.random.randint(5,6,(10,101))
print("2D array:-\n",two_d)
print("shape of array:",np.shape(two_d))
print("total number of elements:",np.size(two_d))
print("data type:",two_d.dtype)

2D array:-
 [[5 5 5 ... 5 5 5]
 [5 5 5 ... 5 5 5]
 [5 5 5 ... 5 5 5]
 ...
 [5 5 5 ... 5 5 5]
 [5 5 5 ... 5 5 5]
 [5 5 5 ... 5 5 5]]
shape of array: (10, 101)
total number of elements: 1010
data type: int64


Q2. (Statistical Methods - Basic)
Generate a 1D array of 20 random numbers between 1 and 50 using
np.random.randint().
Print:
Minimum value and its index (argmin)
Maximum value and its index (argmax)
Sum of all elements
Mean and Standard Deviation

In [38]:
one_d=np.random.randint(1,51,20)
print("1D array:-\n",one_d)
print("minimum value:",np.min(one_d))
print("maximum value:",np.max(one_d))
print("index of minimum value:",np.argmin(one_d))
print("index of maximum value:",np.argmax(one_d))
print("sum of all elements:",np.sum(one_d))
print("mean:",np.mean(one_d))
print("standard deviation:",np.std(one_d))


1D array:-
 [14 31 30  5 32 34  2 39 17 20 34 15 11 49 16  3 25 36 28 26]
minimum value: 2
maximum value: 49
index of minimum value: 6
index of maximum value: 13
sum of all elements: 467
mean: 23.35
standard deviation: 12.491096829342089


Q3. (Statistical Methods on 2D Array)
Create a 4x5 matrix of random integers between 20 and 80.
For the entire matrix, print:
Minimum and maximum value
Sum of all elements
Mean and Standard Deviation
Then print the sum of each row and each column.

In [39]:
matrix=np.random.randint(20,81,(4,5))
print("matrix:-\n",matrix)
print("minimum value:",np.min(matrix))
print("maximum value:",np.max(matrix))
print("sum of all elements:",np.sum(matrix))
print("mean:",np.mean(matrix))
print("standard deviation:",np.std(matrix))
print("sum of each row:",np.sum(matrix,axis=1))
print("sum of each column:",np.sum(matrix,axis=0))

matrix:-
 [[72 54 22 23 29]
 [73 57 53 37 54]
 [56 54 30 28 50]
 [52 46 60 20 59]]
minimum value: 20
maximum value: 73
sum of all elements: 929
mean: 46.45
standard deviation: 15.828692302271845
sum of each row: [200 274 218 237]
sum of each column: [253 211 165 108 192]


Q4. (Reshape)
Create a 1D array containing numbers from 1 to 24 using np.arange().

Reshape it into (4, 6)
Reshape it into (3, 8)
Reshape it into (2, 3, 4) (3D array)
Print all reshaped arrays with their shapes.

In [40]:
array=np.arange(1,25)
print("1D array:-\n",array)
reshape1=array.reshape(4,6)
print("reshaped into (4,6):-\n",reshape1)
reshape2=array.reshape(3,8)
print("reshaped into (3,8):-\n",reshape2)
reshape3=array.reshape(2,3,4)
print("reshaped into (2,3,4):-\n",reshape3)


1D array:-
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
reshaped into (4,6):-
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
reshaped into (3,8):-
 [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
reshaped into (2,3,4):-
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


Q5. (NumPy Indexing - 1D & 2D)
Create the following array:
Python
arr = np.array([[10, 20, 30, 40],
[50, 60, 70, 80],
[90, 100, 110, 120]])
Perform the following indexing:
Extract first row
Extract last column
Extract center 2x2 submatrix
Extract all even numbers from the array using boolean indexing

In [41]:
arr=np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])
print("array:-\n",arr)
first_row=arr[0]
print("first row:-\n",first_row)
last_column=arr[:,-1]
print("last column:-\n",last_column)
center=arr[1:3,1:3]
print("center 2x2 submatrix:-\n",center)
even=arr[arr%2==0]
print("even numbers:-\n",even)

array:-
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
first row:-
 [10 20 30 40]
last column:-
 [ 40  80 120]
center 2x2 submatrix:-
 [[ 60  70]
 [100 110]]
even numbers:-
 [ 10  20  30  40  50  60  70  80  90 100 110 120]


Q6. (Advanced Indexing)
Create a 5x5 matrix of random integers between 1 and 100.
Print the diagonal elements
Print elements greater than 50
Replace all elements less than 30 with 0
Print the modified array

In [8]:
matrix=np.random.randint(1,101,(5,5))
print("matrix:\n",matrix)
diagonal=np.diagonal(matrix)
print("diagonal elements of matrix:\n",diagonal)
elements=matrix[matrix>50]
print("elements greater than 50:\n",elements)
ele=matrix[matrix<30]=0
print("modified array:\n",matrix)

matrix:
 [[33 89 67 40 92]
 [14 65 20 54 95]
 [57 68  8  6  1]
 [24 87 69 62 29]
 [90  3 37 11 23]]
diagonal elements of matrix:
 [33 65  8 62 23]
elements greater than 50:
 [89 67 92 65 54 95 57 68 87 69 62 90]
modified array:
 [[33 89 67 40 92]
 [ 0 65  0 54 95]
 [57 68  0  0  0]
 [ 0 87 69 62  0]
 [90  0 37  0  0]]


Q7. (Arithmetic Operations)
Create two arrays:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])
Perform and print:
Addition, Subtraction, Multiplication, Division
Element-wise power (**)

Modulo operation (%)

In [21]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])
print("array 1:-",a,"\tarray 2:-",b)
#in numpy using the follwinf functions we can perform arithmetic operations
add=np.add(a,b)
print("addition:-",add)
sub=np.subtract(a,b)
print("subtraction:-",sub)
mul=np.multiply(a,b)
print("multiplication:-",mul)
div=np.divide(a,b)
print("division:-",div)
pow=np.power(a,b)
print("power:-",pow)
mod=np.mod(a,b)
print("modulo:-",mod)

array 1:- [10 20 30 40] 	array 2:- [1 2 3 4]
addition:- [11 22 33 44]
subtraction:- [ 9 18 27 36]
multiplication:- [ 10  40  90 160]
division:- [10. 10. 10. 10.]
power:- [     10     400   27000 2560000]
modulo:- [0 0 0 0]


Q8. (Matrix Multiplication)
Create two 3x3 matrices:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[9,8,7],[6,5,4],[3,2,1]])
Perform:
Element-wise multiplication (*)
Matrix multiplication (@ or np.dot())
Print both results and explain the difference in comments.

In [22]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[9,8,7],[6,5,4],[3,2,1]])
# Element-wise multiplication multiplies numbers at matching positions
mul=A*B
print("element wise multiplication:-",mul)
# Matrix multiplication (@) performs the dot product of rows and columns
mat_mul=A@B #or np.dot(A,B)
print("matrix multiplication:-",mat_mul)


element wise multiplication:- [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
matrix multiplication:- [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


Q9. (Combined - Properties + Operations + Indexing)
Generate a 6x6 matrix of random numbers using np.random.randn().
Print its shape, size, and dtype.
Find the index of the maximum and minimum value.
Extract the top-left 3x3 submatrix.
Replace all negative numbers with their absolute value.
Print the mean of the modified matrix.

In [28]:
matrix=np.random.randn(6,6)
print("random 6x6 matrix\n:-",matrix)
shape=np.shape(matrix)
print("\nshape:-",shape)
size=np.size(matrix)
print("\nsize:-",size)
dtype=matrix.dtype
print("\ndtype:-",dtype)
ind_max=np.argmax(matrix)
print("\nindex of maximum value:-",ind_max)
ind_min=np.argmin(matrix)
print("\nindex of minimum value:-",ind_min)
sub_mat=matrix[:3,:3]
print("\ntop-left 3x3 submatrix:-\n",sub_mat)
matrix[matrix<0]=abs(matrix[matrix<0])
print("\nmodified matrix:-\n",matrix)
mean=np.mean(matrix)
print("\nmean of modified matrix:-",mean)


random 6x6 matrix
:- [[ 0.18103579  0.83006624 -1.26653982  0.56690277 -0.59653219  1.95547275]
 [-0.77272443 -0.1176785   0.5942449  -1.10151633 -1.47181458 -0.73445391]
 [-0.84126539 -0.27285214 -1.49311361 -1.72610031  0.6571338  -1.27103863]
 [ 1.55256346 -0.63919661  1.66471229 -1.36018085  0.88279871  0.22366762]
 [-1.19283026  0.22158766 -0.85624593  1.03979076  0.11550952  0.84584332]
 [-1.01052785  1.20112658  0.62553476  1.88405932  0.04631827 -0.78461067]]

shape:- (6, 6)

size:- 36

dtype:- float64

index of maximum value:- 5

index of minimum value:- 15

top-left 3x3 submatrix:-
 [[ 0.18103579  0.83006624 -1.26653982]
 [-0.77272443 -0.1176785   0.5942449 ]
 [-0.84126539 -0.27285214 -1.49311361]]

modified matrix:-
 [[0.18103579 0.83006624 1.26653982 0.56690277 0.59653219 1.95547275]
 [0.77272443 0.1176785  0.5942449  1.10151633 1.47181458 0.73445391]
 [0.84126539 0.27285214 1.49311361 1.72610031 0.6571338  1.27103863]
 [1.55256346 0.63919661 1.66471229 1.36018085 0.8827987

Q10. (Mini Project - Student Performance Analysis)
Create a NumPy-based Student Marks Analyzer:
Generate a 2D array of shape (10 students × 5 subjects) with random marks
between 30 and 100.
Print the array.
For each student, calculate total marks and average.
Find the student with highest and lowest total marks (use argmax/argmin).
Calculate overall class mean and standard deviation.
Reshape the array if needed and demonstrate indexing to extract marks of top
3 students.
Add proper comments explaining each step.

Session 14 (AIML) - Assignment Questions

In [37]:
#students marks analyzer
#generates the random integers matrix of shape (10 students x 5 subject)
arr=np.random.randint(30,101,(10,5))
print("array of shape (10 students × 5 subjects):-\n",arr)
#it returns the total marks and average of each student using axis=1 which define row
total_marks=np.sum(arr,axis=1)
print("\ntotal marks of each student:-",total_marks)
average=np.mean(arr,axis=1)
print("\naverage of each student:-",average)
#argmax() will return the index of the maximum value in the array
highest_total=np.argmax(total_marks)
print("\nstudent with highest total marks:-",highest_total)
#argmin() will return the index of minimun value in the array
lowest_total=np.argmin(total_marks)
print("\nstudent with lowest total marks:-",lowest_total)
#mean() and std() will return the mean and standard deviation of the array
class_mean=np.mean(total_marks)
print("\nclass mean:-",class_mean)
class_std=np.std(total_marks)
print("\nclass standard deviation:-",class_std)
#reshapes the array
reshape=arr.reshape(5,10)
print("\nreshaped array:-",reshape)
#it will sort the array in descending order and return the top 3 students
top_indices = np.argsort(total_marks)[::-1]
top_3=arr[top_indices[:3]]
print("\nmarks of top 3 students:-",top_3)

array of shape (10 students × 5 subjects):-
 [[96 97 76 38 35]
 [79 85 68 61 59]
 [55 34 80 83 49]
 [30 67 68 76 51]
 [40 71 37 86 37]
 [63 80 77 85 92]
 [60 81 46 73 84]
 [78 69 40 41 70]
 [70 36 78 67 72]
 [38 88 36 43 49]]

total marks of each student:- [342 352 301 292 271 397 344 298 323 254]

average of each student:- [68.4 70.4 60.2 58.4 54.2 79.4 68.8 59.6 64.6 50.8]

student with highest total marks:- 5

student with lowest total marks:- 9

class mean:- 317.4

class standard deviation:- 40.42326063048353

reshaped array:- [[96 97 76 38 35 79 85 68 61 59]
 [55 34 80 83 49 30 67 68 76 51]
 [40 71 37 86 37 63 80 77 85 92]
 [60 81 46 73 84 78 69 40 41 70]
 [70 36 78 67 72 38 88 36 43 49]]

marks of top 3 students:- [[63 80 77 85 92]
 [79 85 68 61 59]
 [60 81 46 73 84]]
