<a href="https://colab.research.google.com/github/AqsaAamena/Basic-Python-Projects/blob/main/Assignment_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


Q1. (Basic Array Creation)
Write a program to:
a) Create a 1D array with elements [10, 20, 30, 40, 50] using np.array().
b) Create a 2D array (3x3) using np.array().
Print both arrays along with their shape and data type (dtype).

In [ ]:

one_D=np.array([10,20,30,40,50])
two_D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("1D array:")
print(one_D)
print("Shape:",one_D.shape)
print("Data type:",one_D.dtype)
print("\n2D array:")
print(two_D)
print("Shape:",two_D.shape)
print("Data type:",two_D.dtype)

1D array:
[10 20 30 40 50]
Shape: (5,)
Data type: int64

2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Data type: int64


Q2. (np.zeros() and np.ones())
Create the following using NumPy:
a) A 1D array of 8 zeros.
b) A 2D array of shape (4, 4) filled with ones.
c) A 3x3 matrix of zeros.
Print all arrays with proper labels.

In [ ]:

print("A 1D array of 8 zeros:")
a=np.zeros(8)
print(a)
print("\nA 2D array of shape (4, 4) filled with ones:")
b=np.ones((4,4))
print(b)
print("\nA 3x3 matrix of zeros:")
c=np.zeros((3,3))
print(c)

A 1D array of 8 zeros:
[0. 0. 0. 0. 0. 0. 0. 0.]

A 2D array of shape (4, 4) filled with ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

A 3x3 matrix of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q3. (np.arange())
Use np.arange() to create and print the following arrays:
a) Numbers from 0 to 20 (step 1).
b) Even numbers from 10 to 50.
c) Numbers from 5 to 100 with step of 5.

In [ ]:
#a) Numbers from 0 to 20 (step 1).
arr1=np.arange(0,21,1)
print("Numbers from 0 to 20:\n",arr1)
#b) Even numbers from 10 to 50.
arr2=np.arange(10,51,2)
print("\nEven numbers from 10 to 50:\n",arr2)
#c) Numbers from 5 to 100 with step of 5
arr3=np.arange(5,101,5)
print("\nNumbers from 5 to 100 with step of 5:\n",arr3)

Numbers from 0 to 20:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Even numbers from 10 to 50:
 [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]

Numbers from 5 to 100 with step of 5:
 [  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


Q4. (np.linspace())
Use np.linspace() to create:
a) 10 equally spaced numbers between 0 and 5.
b) 15 equally spaced numbers between -10 and 10.
Print the arrays and their length.

In [ ]:
#a) 10 equally spaced numbers between 0 and 5.
arr1=np.linspace(0,5,10)
print("10 equally spaced numbers between 0 and 5:\n",arr1)
print("\nlength of array:",len(arr1))
#b) 15 equally spaced numbers between -10 and 10.
arr2=np.linspace(-10,10,15)
print("\n\n15 equally spaced numbers between -10 and 10:\n",arr2)
print("\nlength of array:",len(arr2))

10 equally spaced numbers between 0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

length of array: 10


15 equally spaced numbers between -10 and 10:
 [-10.          -8.57142857  -7.14285714  -5.71428571  -4.28571429
  -2.85714286  -1.42857143   0.           1.42857143   2.85714286
   4.28571429   5.71428571   7.14285714   8.57142857  10.        ]

length of array: 15


Q5. (Random Arrays)
Write a program to generate:
a) A 1D array of 10 random numbers between 0 and 1 using np.random.rand().
b) A 3x3 matrix of random numbers from standard normal distribution using
np.random.randn().

c) A 2D array (4x5) of random integers between 10 and 50 using
np.random.randint().
Print all with proper headings.

In [ ]:
#a) A 1D array of 10 random numbers between 0 and 1 using np.random.rand()
one_d=np.random.rand(10)
print(" A 1D array of 10 random numbers between 0 and 1:\n",one_d)
# b) A 3x3 matrix of random numbers from standard normal distribution using np.random.randn().
two_d=np.random.randn(3,3)
print("\nA 3x3 matrix of random numbers from standard normal distribution:\n",two_d)
# c) A 2D array (4x5) of random integers between 10 and 50 using np.random.randint().
three_d=np.random.randint(10,50,(4,5))
print("\nA 2D array (4x5) of random integers between 10 and 50:\n",three_d)

 A 1D array of 10 random numbers between 0 and 1:
 [0.23538964 0.75128158 0.12156708 0.64832475 0.49537569 0.86657216
 0.7019634  0.46299377 0.80155456 0.57516755]

A 3x3 matrix of random numbers from standard normal distribution:
 [[ 1.02296638  1.23762275 -0.04007912]
 [ 0.55137799  1.01365117  0.51161194]
 [-0.90880002 -0.36031375 -0.85058299]]

A 2D array (4x5) of random integers between 10 and 50:
 [[19 35 15 33 17]
 [48 24 13 43 33]
 [20 21 19 18 36]
 [21 11 21 30 28]]


Q6. (Vectors and Basic Operations)
Create two vectors:
v1 = np.array([2, 4, 6, 8])
v2 = np.array([1, 3, 5, 7])
Perform and print:
Addition
Subtraction
Element-wise multiplication
Dot product

In [ ]:
import numpy as np
v1 = np.array([2, 4, 6, 8])
v2 = np.array([1, 3, 5, 7])
print("vector 1:",v1)
print("vector 2:",v2)
add=v1+v2
print("-"*10*3)
print("Addition of vetcor 1 and 2:\n",add)
sub=v1-v2
print("Subtraction of vetcor 1 and 2:\n",sub)
mul=v1*v2
print("Element-wise multiplication of vetcor 1 and 2:\n",mul)
dot=np.dot(v1,v2)
print("Dot product:\n",dot)


vector 1: [2 4 6 8]
vector 2: [1 3 5 7]
------------------------------
Addition of vetcor 1 and 2:
 [ 3  7 11 15]
Subtraction of vetcor 1 and 2:
 [1 1 1 1]
Element-wise multiplication of vetcor 1 and 2:
 [ 2 12 30 56]
Dot product:
 100


Q7. (Matrices and Operations)
Create two 3x3 matrices:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[9,8,7],[6,5,4],[3,2,1]])
Perform the following:
Matrix addition
Matrix multiplication (@ or np.dot())
Element-wise multiplication (*)
Print the results clearly.

In [ ]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[9,8,7],[6,5,4],[3,2,1]])
print("Matrix 1:\n",A)
print("Matrix 2:\n",B)
add=A + B
print("\n----Matrix addition----")
print(add)
dot=A @ B #or np.dot(A,B)
print("\n----Matrix multiplication----")
print(dot)
mul=A * B
print("\n----Element-wise multiplication----")
print(mul)

Matrix 1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix 2:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]

----Matrix addition----
[[10 10 10]
 [10 10 10]
 [10 10 10]]

----Matrix multiplication----
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

----Element-wise multiplication----
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


Q8. (Properties of Arrays)
Create a 4x4 matrix of random integers between 1 and 100.
Print:
Shape
Dimension (ndim)
Total number of elements (size)
Data type

Minimum and maximum values

In [ ]:
arr=np.random.randint(1,101,(4,4))
print("Matrix:\n",arr)
print("\nShape:",arr.shape)
print("Dimension (ndim):",arr.ndim)
print("Total number of elements (size):",arr.size)
print("Data type:",arr.dtype)
print("Minimum values:",arr.min())
print("Maximum values:",arr.max())

Matrix:
 [[67 48 36 37]
 [53 96 13 74]
 [57 86 46 46]
 [10 46 67 43]]

Shape: (4, 4)
Dimension (ndim): 2
Total number of elements (size): 16
Data type: int64
Minimum values: 10
Maximum values: 96


Q9. (Combined - Random + Reshape + Statistics)
Generate a 1D array of 20 random integers between 1 and 50 using
np.random.randint().
Reshape it into a 4x5 matrix.
Print the sum, mean, and standard deviation of the matrix.
Find the maximum value in each row.

In [ ]:
import numpy as np
arr=np.random.randint(1,51,20)
print("1D array:")
print(arr)
reshape=arr.reshape(4,5)
print("Reshaped 4x5 matrix:")
print(reshape)
sum=reshape.sum()
print("sum of matrix:-",sum)
mean=reshape.mean()
print("mean of matrix:-",mean)
std=np.std(reshape)
print("Standard deviation:-",std)
max=reshape.max(axis=1)
print("maximum value in each row:-",max)

1D array:
[ 2 16 39 20  9  2 47  4 19  4  1 10  7 23 31 36 18 24 27 43]
Reshaped 4x5 matrix:
[[ 2 16 39 20  9]
 [ 2 47  4 19  4]
 [ 1 10  7 23 31]
 [36 18 24 27 43]]
sum of matrix:- 382
mean of matrix:- 19.1
Standard deviation:- 14.117011015083893
maximum value in each row:- [39 47 31 43]


Q10. (Mini Project - NumPy Application)
Create a Simple Statistics Calculator using NumPy:
Write a program that:
Asks the user how many numbers they want to generate.
Generates that many random numbers between 10 and 100 using
np.random.randint().
Stores them in a 1D array.
Prints:
The array
Mean, Median, Standard Deviation
Minimum and Maximum
Reshapes into a 2D array (if possible) and prints row-wise sum.
Use proper comments and exception handling where needed.

In [ ]:
import numpy as np
num=int(input("How many numbers you want to generate:"))
#use to generate random integers
arr=np.random.randint(10,101,num)
print("Array:",arr)
# methods to print basic statistics
mean=arr.mean()
print("Mean:",mean)
median=np.median(arr)
print("Median:",median)
std=np.std(arr)
print("Standard Deviation:",std)
min=arr.min()
print("Minimum:",min)
max=arr.max()
print("Maximum:",max)
factors = [i for i in range(2, num) if num % i == 0]
try:
  if len(factors) > 0:
    rows = factors[len(factors) // 2]
    cols = num // rows
    two_d = arr.reshape(rows, cols)
    print(f"\nArray reshaped into a {rows}x{cols} matrix:\n", two_d)
    row_sum = two_d.sum(axis=1)
    print("Row-wise sum:", row_sum)
  else:
    raise ValueError
except ValueError:
  print(f"ValueError: cannot reshape array of size {num} into shape ({rows},{cols})")


How many numbers you want to generate:6
Array: [68 99 17 55 43 35]
Mean: 52.833333333333336
Median: 49.0
Standard Deviation: 26.02829656781677
Minimum: 17
Maximum: 99

Array reshaped into a 3x2 matrix:
 [[68 99]
 [17 55]
 [43 35]]
Row-wise sum: [167  72  78]
